[INFO / 2023-05-03 05:47:36] Running pre-analysis hooks for project test2 (7a09f6475a2640f3afb09f1bd596e631).
[INFO / 2023-05-03 05:47:36] Fetching data for project test2 (7a09f6475a2640f3afb09f1bd596e631).
[ERROR / 2023-05-03 05:47:36] Fetching data for project test2 (7a09f6475a2640f3afb09f1bd596e631) failed!
[ERROR / 2023-05-03 05:47:36] Analysis of project test2 (7a09f6475a2640f3afb09f1bd596e631) failed!
[ERROR / 2023-05-03 05:47:36] Traceback (most recent call last):
  File "/srv/scanmycode/quantifiedcode/backend/tasks/project/analyze.py", line 42, in hook_step
    settings.hooks.call(hook, project)
  File "/srv/scanmycode/quantifiedcode/helpers/hooks.py", line 42, in call
    hook(*args, **kwargs)
  File "/srv/scanmycode/quantifiedcode/plugins/git/backend/tasks/fetch.py", line 71, in fetch_remote
    shutil.copytree(repository.path, tmp_repo_path)
  File "/usr/local/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/srv/scanmycode/quantifiedcode/data/repositories/b3faab4b3732468f9f3786ec79682400'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/scanmycode/quantifiedcode/backend/tasks/project/analyze.py", line 76, in analyze_project
    _analyze_project(project)
  File "/srv/scanmycode/quantifiedcode/backend/tasks/project/analyze.py", line 92, in _analyze_project
    hook_step(project, "project.analyze.fetch", "Fetching data")
  File "/srv/scanmycode/quantifiedcode/backend/tasks/project/analyze.py", line 45, in hook_step
    logger.error("Exception {} {}.".format(e.__class__.__name__, e.message))
AttributeError: 'FileNotFoundError' object has no attribute 'message'

